from __future__ import annotations

import json
import re
import time
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Optional
from urllib.parse import urlencode, urljoin, urlparse

from tourism_weather_ml.aws.clients import AwsClients
from tourism_weather_ml.config import Settings
from tourism_weather_ml.ingestion.dataestur_catalog import (
    IDEAL_DATAESTUR_ENDPOINT_NAMES,
    endpoint_name,
)


@dataclass(frozen=True)
class DataesturDownload:
    name: str
    url: str
    local_path: Path
    metadata_path: Path
    s3_bronze_original_key: Optional[str]
    s3_bronze_metadata_key: Optional[str]
    s3_bronze_manifest_key: Optional[str]
    content_type: str
    bytes_written: int


@dataclass(frozen=True)
class DataesturPlannedDownload:
    name: str
    endpoint_or_url: str
    url: str
    local_dir: Path
    s3_bronze_original_prefix: str
    s3_bronze_manifest_prefix: str


class DataesturClient:
    """Downloads Dataestur API endpoints into the bronze landing zone.

    The API exposes file download endpoints such as EOH_PROV_DL. The client also
    accepts explicit Request URLs generated by the Dataestur UI for filtered
    queries.
    """

    def __init__(
        self,
        settings: Settings,
        clients: AwsClients,
        output_dir: Path = Path("datasets/bronze/dataestur/original"),
        min_seconds_between_requests: float = 6.5,
        timeout_seconds: int = 300,
    ) -> None:
        self.settings = settings
        self.clients = clients
        self.output_dir = output_dir
        self.min_seconds_between_requests = min_seconds_between_requests
        self.timeout_seconds = timeout_seconds

    def plan_configured_sources(
        self,
        endpoints: tuple[str, ...] | None = None,
        limit: int | None = None,
    ) -> list[DataesturPlannedDownload]:
        configured_sources = self._configured_sources(endpoints=endpoints, limit=limit)
        bucket = self.settings.s3_bucket_name or "<S3_BUCKET_NAME>"
        return [
            DataesturPlannedDownload(
                name=name,
                endpoint_or_url=endpoint_or_url,
                url=url,
                local_dir=self.output_dir,
                s3_bronze_original_prefix=(
                    f"s3://{bucket}/{self.settings.s3_bronze_prefix}/dataestur/original/"
                ),
                s3_bronze_manifest_prefix=(
                    f"s3://{bucket}/{self.settings.s3_bronze_prefix}/dataestur/landing_manifest/"
                ),
            )
            for name, endpoint_or_url, url in configured_sources
        ]

    def download_configured_sources(
        self,
        upload_to_s3: bool = True,
        endpoints: tuple[str, ...] | None = None,
        limit: int | None = None,
    ) -> list[DataesturDownload]:
        configured_sources = self._configured_sources(endpoints=endpoints, limit=limit)
        if not configured_sources:
            return []

        self.output_dir.mkdir(parents=True, exist_ok=True)
        downloads: list[DataesturDownload] = []
        for index, (name, _endpoint_or_url, url) in enumerate(configured_sources):
            if index:
                time.sleep(self.min_seconds_between_requests)
            downloads.append(self.download(name=name, url=url, upload_to_s3=upload_to_s3))
        return downloads

    def download_configured_urls(self, upload_to_s3: bool = True) -> list[DataesturDownload]:
        return self.download_configured_sources(upload_to_s3=upload_to_s3)

    def build_endpoint_url(self, endpoint: str) -> str:
        clean_endpoint = endpoint.strip().strip("/")
        base_url = self.settings.dataestur_base_url.rstrip("/") + "/"
        url = urljoin(base_url, clean_endpoint)
        params = self._default_query_params()
        if not params:
            return url
        return f"{url}?{urlencode(params)}"

    def download(self, name: str, url: str, upload_to_s3: bool = True) -> DataesturDownload:
        self._validate_url(url)
        response = self._get(url)
        content_type = response.headers.get("content-type", "application/octet-stream")
        suffix = self._guess_suffix(url=url, content_type=content_type, content=response.content)
        downloaded_at = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
        local_path = self.output_dir / f"{self._output_stem(name)}{suffix}"
        self._validate_response_content(response.content, suffix=suffix, content_type=content_type)
        local_path.write_bytes(response.content)

        metadata_path = local_path.with_suffix(local_path.suffix + ".metadata.json")
        metadata_path.write_text(
            json.dumps(
                {
                    "source": "dataestur",
                    "name": name,
                    "url": url,
                    "downloaded_at": downloaded_at,
                    "overwrite_mode": True,
                    "content_type": content_type,
                    "bytes_written": len(response.content),
                    "local_path": str(local_path),
                },
                indent=2,
                ensure_ascii=False,
            ),
            encoding="utf-8",
        )

        s3_bronze_original_key = None
        s3_bronze_metadata_key = None
        s3_bronze_manifest_key = None
        if upload_to_s3 and self.settings.s3_bucket_name:
            s3_bronze_original_key = (
                f"{self.settings.s3_bronze_prefix}/dataestur/original/{local_path.name}"
            )
            s3_bronze_metadata_key = f"{s3_bronze_original_key}.metadata.json"
            s3_bronze_manifest_key = (
                f"{self.settings.s3_bronze_prefix}/dataestur/landing_manifest/"
                f"{metadata_path.name}"
            )
            self.clients.s3.upload_file(
                str(local_path),
                self.settings.s3_bucket_name,
                s3_bronze_original_key,
            )
            self.clients.s3.upload_file(
                str(metadata_path),
                self.settings.s3_bucket_name,
                s3_bronze_metadata_key,
            )
            self.clients.s3.upload_file(
                str(metadata_path),
                self.settings.s3_bucket_name,
                s3_bronze_manifest_key,
            )

        return DataesturDownload(
            name=name,
            url=url,
            local_path=local_path,
            metadata_path=metadata_path,
            s3_bronze_original_key=s3_bronze_original_key,
            s3_bronze_metadata_key=s3_bronze_metadata_key,
            s3_bronze_manifest_key=s3_bronze_manifest_key,
            content_type=content_type,
            bytes_written=len(response.content),
        )

    def _get(self, url: str):
        try:
            import requests
        except ImportError as exc:
            raise RuntimeError("Install dependencies with `pip install -r requirements.txt`.") from exc

        response = requests.get(url, timeout=self.timeout_seconds)
        if response.status_code == 429:
            raise RuntimeError("Dataestur returned 429 Too Many Requests. Retry later or lower frequency.")
        response.raise_for_status()
        return response

    def _configured_sources(
        self,
        endpoints: tuple[str, ...] | None = None,
        limit: int | None = None,
    ) -> list[tuple[str, str, str]]:
        selected_endpoints = endpoints or self.settings.dataestur_endpoints or IDEAL_DATAESTUR_ENDPOINT_NAMES
        sources = [
            (endpoint_name(endpoint), endpoint.strip().strip("/"), self.build_endpoint_url(endpoint))
            for endpoint in selected_endpoints
            if endpoint.strip()
        ]
        sources.extend(
            (name, url, url) for name, url in self.settings.dataestur_request_urls.items()
        )
        return sources[:limit] if limit is not None else sources

    @staticmethod
    def _validate_url(url: str) -> None:
        parsed = urlparse(url)
        if parsed.scheme != "https":
            raise ValueError("Dataestur request URLs must use HTTPS.")
        allowed_hosts = ("dataestur.es", "dataestur.azure-api.net")
        if not parsed.netloc.endswith(allowed_hosts):
            raise ValueError("Only Dataestur URLs are accepted for the Dataestur client.")

    def _default_query_params(self) -> dict[str, int]:
        params: dict[str, int] = {}
        if self.settings.dataestur_from_year is not None:
            params["desde (año)"] = self.settings.dataestur_from_year
        if self.settings.dataestur_from_month is not None:
            params["desde (mes)"] = self.settings.dataestur_from_month
        if self.settings.dataestur_to_year is not None:
            params["hasta (año)"] = self.settings.dataestur_to_year
        if self.settings.dataestur_to_month is not None:
            params["hasta (mes)"] = self.settings.dataestur_to_month
        return params

    @staticmethod
    def _guess_suffix(url: str, content_type: str, content: bytes = b"") -> str:
        parsed_path = Path(urlparse(url).path)
        if parsed_path.suffix:
            return parsed_path.suffix
        if "spreadsheet" in content_type or "excel" in content_type:
            return ".xlsx"
        if "json" in content_type:
            return ".json"
        if "csv" in content_type:
            return ".csv"
        if DataesturClient._looks_like_semicolon_csv(content):
            return ".csv"
        return ".bin"

    def _output_stem(self, name: str) -> str:
        safe_name = re.sub(r"[^a-zA-Z0-9_]+", "_", name).strip("_").lower()
        if (
            self.settings.dataestur_from_year is not None
            and self.settings.dataestur_from_month is not None
            and self.settings.dataestur_to_year is not None
            and self.settings.dataestur_to_month is not None
        ):
            start = f"{self.settings.dataestur_from_year:04d}{self.settings.dataestur_from_month:02d}"
            end = f"{self.settings.dataestur_to_year:04d}{self.settings.dataestur_to_month:02d}"
            return f"{safe_name}_{start}_{end}"
        return safe_name

    @staticmethod
    def _validate_response_content(content: bytes, suffix: str, content_type: str) -> None:
        if len(content) < 100:
            raise RuntimeError("Dataestur response is unexpectedly small.")
        if content.lstrip().lower().startswith(b"<!doctype html") or content.lstrip().lower().startswith(b"<html"):
            raise RuntimeError("Dataestur returned HTML instead of a data file.")
        if suffix == ".xlsx" and not content.startswith(b"PK"):
            raise RuntimeError(f"Dataestur response content-type={content_type} is not a valid XLSX file.")

    @staticmethod
    def _looks_like_semicolon_csv(content: bytes) -> bool:
        head = content[:2048]
        if not head or b";" not in head:
            return False
        try:
            text = head.decode("utf-8")
        except UnicodeDecodeError:
            text = head.decode("latin-1", errors="ignore")
        first_line = text.splitlines()[0] if text.splitlines() else ""
        return ";" in first_line and ("AÑO" in first_line or "A\xd1O" in first_line or "MES" in first_line)
